server:
  port: 80
spring:
  application:
    name: cloud-order-service
  mvc:
    servlet:
      load-on-startup: 1
eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认是true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认是true。单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka